name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          CHROME_BIN: ./node_modules/chromium/lib/chromium/chrome-linux/chrome
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox

      - name: Run lint
        run: npm run lint

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /bookmarky/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/bookmarky

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
